Work around MinGW 4.8 bug with NULL comparison
x86_64-w64-mingw32-g++ 4.8.2 gives a bogus

error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

for the old code comparing get_name() and NULL (in 64 bits only,
strangely enough).

Instead of working around this weird problem, just remove comparison
with NULL, it's not useful anyhow.